### ISSUE TITLE
"Jittery" MP4 video - when played with QT Player, but not VLC

### ISSUE THREAD

**Issue by Jimw338** [mi-g/vdhcoapp#33] opened 2018-06-17 02:49 UTC
I don't know if this is answered somewhere else - sorry if it is, but at least this question will be here if anyone else is looking for this answer.  I've had some downloads with VideoDownloadHelper that are "jittery" when played with OSX Quicktime Player (or the QuickLook plugin, which I assume uses the same class), but not when played with VLC (I assume uses it's own decoding engine).

I don't know much about how the MPEG spec works, but it looks like it might be doing something where it mis-orders the key-frames somehow, so instead of seeing (this is my guess as to how things are coded) "(keyframe A)-[diff A]-(KF B)-[diff B]" where [diff] is the encoded difference information for whatever time-slicing is used, it goes "(KF A)-[diff A]-(KF A)-(KF B)-[diff B]"

But it seems odd that QT player displays it "jittery", but VLC doesn't - is VLC "non-compliant" with the spec in some way that hides the artifact?

Thanks,

**Comment by mi-g** [comment] 2018-06-17 07:06
This is a known issue in Video DownloadHelper. You can find several references to this problem from the add-on [support forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/video-downloadhelper-q-and-a). For now, the workarounds are to either use a video player other than QT, or re-encode the file.

Anyway, the problem is not with the coapp as the generation of the video file is done in the extension (the coapp just writes blocks to the disk). So i close this issue from the vdhcoapp project.

**Closed by mi-g** 2018-06-17 07:06 UTC
